/* ---------------------------------------------------------------------------
   The Weekly Commander Brief's shape. Pure and I/O-free — this is the JSON
   stored in agent_runs.output and rendered by /admin/brief and the Monday
   email. Language-neutral by design: names, numbers and dates only, so one
   stored run reads correctly in either language and a brief generated in
   English needs no regenerating to be read in Ukrainian.

   lib/weekly-brief.ts builds it; this half only says what it is.
--------------------------------------------------------------------------- */

export type BriefStockLine = { sku: string; nameEn: string; nameUk: string; onHand: number };

export type BriefSuggestion = {
  sku: string;
  nameEn: string;
  nameUk: string;
  suggested: number;
  status: "critical" | "low" | "ok" | "overstock";
};

export type BriefTopProduct = {
  sku: string;
  name: string;
  units: number;
  revenueUah: number | null;
};

export type BriefData = {
  /** Kyiv date the brief was generated. */
  generatedOn: string;

  week: {
    /** The trailing seven Kyiv days, inclusive. */
    from: string;
    to: string;
    revenueUah: number;
    orders: number;
    /** Orders counted but not summed — no amount_uah on the row. */
    unpriced: number;
    /** The seven days before those, for the "up or down" glance. */
    prevRevenueUah: number;
    prevOrders: number;
  };

  /** This Kyiv month so far, straight from finance_monthly (0018). Null when
      the month has no rows yet or finance was unreadable at build time. */
  monthToDate: {
    month: string;
    ordersCount: number;
    revenueUah: number | null;
    cogsUah: number | null;
    opexUah: number | null;
    marginUah: number;
    uncostedLines: number;
    unpricedOrders: number;
  } | null;

  /** Best sellers of the week, by revenue. */
  topProducts: BriefTopProduct[];

  stock: {
    critical: BriefStockLine[];
    low: BriefStockLine[];
    overstock: BriefStockLine[];
    /** What the Stock Advisor would produce, biggest first. */
    suggestions: BriefSuggestion[];
  };

  wholesale: {
    /** Partners whose next_follow_up is today or past. */
    dueFollowUps: number;
    /** Quiet partners (the Follow-up Agent's list), quietest first. */
    quiet: { company: string; daysQuiet: number; status: string }[];
  };
};

/**
 * Is this stored agent_runs.output a brief this code can render? Old runs
 * outlive rewrites of the shape above; a version check keeps them from
 * crashing the page — an unreadable run renders as "generated by an earlier
 * version", which is the truth.
 */
export function isBriefData(v: unknown): v is BriefData {
  if (typeof v !== "object" || v === null) return false;
  const o = v as Record<string, unknown>;
  return (
    typeof o.generatedOn === "string" &&
    typeof o.week === "object" &&
    o.week !== null &&
    typeof o.stock === "object" &&
    o.stock !== null &&
    typeof o.wholesale === "object" &&
    o.wholesale !== null &&
    Array.isArray(o.topProducts)
  );
}

/** ₴1 234, or — for unknown. The founder's numbers are never invented zeros. */
export function briefUah(n: number | null): string {
  if (n === null) return "—";
  return `₴${Math.round(n).toLocaleString("uk-UA")}`;
}

/** "+12%" / "−8%" / "—" against the previous week. */
export function weekDelta(now: number, prev: number): string {
  if (prev <= 0) return "—";
  const pct = Math.round(((now - prev) / prev) * 100);
  return pct >= 0 ? `+${pct}%` : `−${Math.abs(pct)}%`;
}
