#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Regenerate the pouch QR codes from the slugs in lib/products.ts.

    python3 scripts/build-qr.py

WHY THIS IS A SCRIPT AND NOT TWO FILES SOMEBODY MADE ONCE. The whole point of
these codes is that they are printed on a pouch and cannot be corrected
afterwards. A code is only as good as the URL inside it, so the URL is read from
the catalogue rather than typed here: rename a slug and this fails loudly
instead of shipping a code that 404s on a product nobody can reach.

WHAT THE SETTINGS MEAN FOR PRINT.

  ERROR CORRECTION H (30%). The highest level. A pouch gets creased, rubbed and
  wet, and a code that has lost a corner should still scan. It costs modules —
  the symbol is denser — which is why the URLs are kept short.

  QUIET ZONE 4 MODULES. The spec's minimum, and the single most common reason a
  printed code fails: the white margin is part of the symbol, and a designer who
  crops to the black edge breaks it. It is baked in here so it cannot be lost.

  PURE BLACK ON PURE WHITE. Not the brand orange, not the cream. Scanners
  threshold on luminance, and the packaging orange against cream measures far
  too close to read reliably under a shop's lighting. The code is a machine
  target, not a brand surface.

  SVG AS WELL AS PNG. The PNG is for proofing on screen; the SVG is what should
  go to the printer, because it stays sharp at any size. The PNG is deliberately
  large (~1000px) so nobody scales one up and prints a soft code.
"""

import os
import re
import sys

try:
    import segno
except ImportError:
    sys.exit("segno is not installed:  python3 -m pip install segno")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "qr")

SITE = os.environ.get("QR_SITE", "https://tactical-hb.com")

# The EN storefront is the canonical target: there is no locale-neutral product
# route in this app (every page lives under /[locale]), so a code has to name
# one. English is the export storefront and the one a scanner anywhere outside
# Ukraine should land on; the switcher on the page reaches the other three.
LOCALE = os.environ.get("QR_LOCALE", "en")

# Slug → the file stem. The slug is VERIFIED against the catalogue below; it is
# not the source of truth, only the thing being checked.
TARGETS = [
    ("fear-9e418", "qr-fear-9e418"),
    ("lid-9e418", "qr-lid-9e418"),
]


def catalogue_slugs():
    """Every slug lib/products.ts actually defines."""
    src = open(os.path.join(ROOT, "lib", "products.ts"), encoding="utf-8").read()
    # Only the exported `products` array — featuredProducts re-lists by slug.
    start = src.index("export const products")
    end = src.index("const bySlug")
    return set(re.findall(r'slug:\s*"([^"]+)"', src[start:end]))


def main():
    known = catalogue_slugs()
    missing = [s for s, _ in TARGETS if s not in known]
    if missing:
        sys.exit(
            "These slugs are not in lib/products.ts: %s\n"
            "A QR code for a product that does not exist would print a 404 onto a "
            "pouch. Fix the slug here or in the catalogue before regenerating."
            % ", ".join(missing)
        )

    os.makedirs(OUT, exist_ok=True)
    lines = []

    for slug, stem in TARGETS:
        url = "%s/%s/products/%s" % (SITE.rstrip("/"), LOCALE, slug)
        qr = segno.make(url, error="h")

        png = os.path.join(OUT, stem + ".png")
        svg = os.path.join(OUT, stem + ".svg")
        # scale 20 on a 25-module symbol lands around 1000px including the border.
        qr.save(png, scale=20, border=4, dark="#000000", light="#FFFFFF")
        qr.save(svg, scale=20, border=4, dark="#000000", light="#FFFFFF")

        size = qr.symbol_size(scale=20, border=4)
        lines.append((stem, url, qr.version, "%dx%d" % size))
        print("  %-18s %s" % (stem, url))
        print("     version %-3s %s px  ec=H  quiet zone=4" % (qr.version, "%dx%d" % size))

    readme = os.path.join(OUT, "README.md")
    with open(readme, "w", encoding="utf-8") as f:
        f.write("# Pouch QR codes\n\n")
        f.write("Generated by `scripts/build-qr.py`. Do not edit these files by hand —\n")
        f.write("regenerate them, so the encoded URL always matches the catalogue.\n\n")
        f.write("| File | Encodes | Version | Size |\n|---|---|---|---|\n")
        for stem, url, version, size in lines:
            f.write("| `%s.png` / `.svg` | %s | %s | %s px |\n" % (stem, url, version, size))
        f.write("\n## For the printer\n\n")
        f.write("- Send the **SVG**. The PNG is for on-screen proofing.\n")
        f.write("- Error correction **H** (30%), quiet zone **4 modules** — already in the file.\n")
        f.write("- **Do not crop to the black edge.** The white margin is part of the symbol.\n")
        f.write("- **Do not recolour.** Pure black on pure white; the brand orange does not\n")
        f.write("  carry enough luminance contrast to scan reliably.\n")
        f.write("- Print at 20 mm or larger on the pouch, and test-scan the proof.\n\n")
        f.write("## If a slug ever changes\n\n")
        f.write("Codes already printed cannot be changed. Keep the old slug working —\n")
        f.write("`lib/products.ts` is where these URLs come from, and this script refuses\n")
        f.write("to build a code for a slug the catalogue does not define.\n")

    print("\n  wrote %d files + README to docs/qr/" % (len(TARGETS) * 2))


if __name__ == "__main__":
    main()
