-- =============================================================================
--  RETIRED — this migration is intentionally a no-op. Do not restore it.
--
--  It used to seed three fake orders (EUR 24.40 / 50.30 / 43.80) against a
--  named account, to give the loyalty pages something to render before real
--  orders existed. Inserting them fired the loyalty trigger, so it also awarded
--  1185 XP and issued a EUR 10 milestone voucher.
--
--  Those rows were deleted on 2026-07-24, along with the XP and voucher they
--  produced, once the shop had real paid orders and an admin orders page to
--  read them. Re-running the seed would put fabricated orders back into a live
--  shop — they'd appear in /admin/orders next to genuine ones, and inflate a
--  real customer's loyalty balance.
--
--  The file is kept (rather than deleted) so the migration numbering and the
--  history of what was applied stay intact. If you need demo data again, seed a
--  separate non-production database instead.
--
--  Expected result: "Success. No rows returned."
-- =============================================================================

-- Deliberately empty.
